using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TVManager : MonoBehaviour
{
    public GameObject Tv80;

    public GameObject Tv70;

    private void Awake()
    {
        //Debug.Log("BEN ㈋K UYANDIIMDA 큐LIケN METODUM.");
    }

    void Start()
    {
        //Debug.Log("BEN ㈋K SAN㈘E 큐LIケN METODUM.");       
    }

    private void OnEnable()
    {
        //Debug.Log("BEN BALI OLDUUM OBJE ㈋K 큐LIツIINDA 큐LIケN METODUM.");

        Tv70.SetActive(true);
        Tv80.SetActive(false);
    }

    void Update()
    {
        //Debug.Log("BEN ㈋K HER SAN㈘E 큐LIケN METODUM.");
    }

    private void OnDisable()
    {
        //Debug.Log("BEN BALI OLDUUM OBJE KAPANDIINDA 큐LIケN METODUM.");

        //Tv80.SetActive(true);
        //Tv70.SetActive(false);
    }
}
